name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - run: npm ci
      - name: Run ESLint
        run: npx eslint